# 这个文件是 Ruff 的配置文件
# 它支持 TOML 和 YAML 格式
# 我们使用 TOML 格式，因为它更简洁

[tool.ruff]
# 全局配置，比如行长，可以留在这里
line-length = 88

# 把所有 lint (检查) 相关的配置挪到这个新分组里
[tool.ruff.lint]
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []
select = ["E", "F", "I"]
ignore = []

# format (格式化) 部分保持不变
[tool.ruff.format]
quote-style = "double"